// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by: tool/generate_routes.dart

class AppRoutes {
  const AppRoutes._();

  static const String splashName = 'splash';
  static const String splashPath = '/';

  static const String homeName = 'home';
  static const String homePath = '/home';

  static const String resultsName = 'results';
  static const String resultsPath = '/results';

  static const String savedPlantsName = 'savedPlants';
  static const String savedPlantsPath = '/saved-plants';

  static const String chatbotName = 'chatbot';
  static const String chatbotPath = '/chatbot';

  static const String cameraName = 'camera';
  static const String cameraPath = '/camera';
}
