import 'dart:convert';
import 'dart:io';

void main() async {
  final routesFile = File('tool/routes.json');
  if (!routesFile.existsSync()) {
    stderr.writeln('Missing tool/routes.json');
    exitCode = 1;
    return;
  }

  final content = await routesFile.readAsString();
  final routes = (jsonDecode(content) as List<dynamic>)
      .whereType<Map>()
      .map((e) => Map<String, dynamic>.from(e))
      .toList();

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('// Generated by: tool/generate_routes.dart')
    ..writeln()
    ..writeln('class AppRoutes {')
    ..writeln('  const AppRoutes._();')
    ..writeln();

  for (final route in routes) {
    final name = route['name']?.toString() ?? '';
    final path = route['path']?.toString() ?? '';
    if (name.isEmpty || path.isEmpty) continue;
    final constant = _constantCase(name);
    buffer
      ..writeln("  static const String ${constant}Name = '$name';")
      ..writeln("  static const String ${constant}Path = '$path';")
      ..writeln();
  }

  buffer.writeln('}');

  final targetFile = File('lib/core/routing/app_routes.g.dart');
  await targetFile.create(recursive: true);
  await targetFile.writeAsString(buffer.toString());
  stdout.writeln('Generated ${targetFile.path}');
}

String _constantCase(String value) {
  if (value.isEmpty) return value;
  return value[0].toLowerCase() + value.substring(1);
}
